name: Run JUnit Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  # <-- add this line. This creates the button

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build and Test
      run: mvn -B clean test --file pom.xml
